[package]
name = "proxide"
version = "0.0.1"
edition = "2021"

[dependencies]
graphql_client = { version = "0.13.0", features = ["reqwest"] }
chrono = { version = "0.4.30", features = ["serde"] }
thiserror = "1.0.48"
reqwest = "0.11.20"
serde = "1.0.188"
