name: Publish

on:
  push:
    tags:
      - v*

env:
  DOCKER_IMAGE_NAME: ${{ github.repository }}
  DOCKER_REGISTRY: ghcr.io
  RUST_VERSION: 1.72.0

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Cargo Check
        run: cargo check

      - name: Cargo Test
        run: cargo test --all

  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}

      - name: Extract Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          target: runtime
          push: true
